#Genetic Algorithm
What are we doing?

Imagine you're going on a treasure hunt. Your bag can carry only a limited weight, but there are various items with different weights and values. The goal is to pack the bag with items that give you the most value without exceeding the weight limit. We will use Genetic Algorithms to solve this problem.


The below example consist of packing a bag using some items chosen from the list below. The value of each item is based on the number of likes on a E-Commerce website.

<img src = 'https://drive.google.com/uc?id=1GCfDsCiABip8QSGYOHBhG190FWzHIbpE' width = 600>

<img src = 'https://drive.google.com/uc?id=1hAec8qFAh9_OAUxyuPUXswMK1vf2I3Zy' width = 600>

The first step in using genetic algorithm is to encode the data into gene.
Here, the gene will consist of 0s and 1s. So, we’ll represent the solution as a string of 0s and 1s.

1: item packed

0: item not packed


For instance in the below sample, we're only packing the phone, mints, laptop, tissues, and the water bottle.

<img src = 'https://drive.google.com/uc?id=1lHCO2DK8Psj8GNvalzVhEaM4ddi30eaV' width = 600>

This combination gives us a total value packed of 1050 as shown below:

<img src = 'https://drive.google.com/uc?id=1kGkPzq-AWXQGYYoRtJD8S6_hqaqq9iAm' width = 600>

The below is just an example on how to use a fitness function, i.e., $f(x) = x^2$ to solve similar optimization problems to get the optimal solution possible.


#Generating the population

In this examle, we'll use the fitness function $f(x) = x^2$  to guide our simulations towards optimal design solutions.

In [1]:
import numpy as np
import pandas as pd

initial_population = np.array ([
    [0, 1, 0, 1, 0, 0, 1, 0, 1, 1],
    [1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [1, 0, 1, 1, 0, 1, 0, 1, 1, 0],
    [1, 0, 1, 0, 0, 1, 1, 0, 1, 1]])

print(initial_population)

[[0 1 0 1 0 0 1 0 1 1]
 [1 1 1 1 1 0 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 0 1 0 1 1 0]
 [1 0 1 0 0 1 1 0 1 1]]


#Compute the fitness scores

The fitness scores are comparable to the example value we had by packing for instance the phone, mints, laptop, tissues, and the water bottle in the previously.

In [2]:
def fitness(x):
  return sum(x)**2

In [3]:
fitness_scores = np.apply_along_axis(fitness, 1, initial_population)
fitness_scores

array([25, 81, 64, 36, 36])

#Selection
We're selecting the individuals with the highest fitness score in descending order.

In [5]:
def select_parents(fitness_scores):
    parents = np.argsort(fitness_scores)[-2:][::-1]
    return parents

selected_parents = select_parents(fitness_scores)
selected_parents

array([1, 2])

#Crossover

In [6]:
def crossover(parent1, parent2):
    crossover_point = np.random.randint(1, len(parent1) - 1)
    print(crossover_point)
    child = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    return child



child = crossover(initial_population[selected_parents[0]], initial_population[selected_parents[1]])
child

3


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

# Mutation
To maintain diversity, we apply random mutations:

In [7]:
def mutate(child):
    mutation_point = np.random.randint(len(child))

    child[mutation_point] = 1 - child[mutation_point]
    print(mutation_point)

    return child
print("Original: ", child)
mutated_child = mutate(child)
print("Mutated:  ",mutated_child)

Original:  [1 1 1 1 1 1 1 1 1 0]
9
Mutated:   [1 1 1 1 1 1 1 1 1 1]


In [8]:
def elitism(population, fitness_scores, elite_size=2):
    elite_indices = np.argsort(fitness_scores)[-elite_size:]

    elite_individuals = population[elite_indices]
     #2:[0 1 1 1 1 1 1 1 1 0] and 1:[1 1 1 1 1 1 1 1 1 0]
    return elite_individuals

# Initialize variables
generations = 10
population = initial_population
population_size = 20
chromosome_length = 10

# Loop through each generation
for generation in range(generations):
    # Calculate fitness
    fitness_scores = np.apply_along_axis(fitness, 1, population)

    # Elitism: Select top individuals
    elites = elitism(population, fitness_scores)

    # Selection
    selected_parents_indices = select_parents(fitness_scores)
    selected_parents = population[selected_parents_indices]

    # Crossover and Mutation
    children = []
    while len(children) < population_size - len(elites):
        parent1, parent2 = selected_parents
         #parent1, parent2 = [1, 2]
        child = crossover(parent1, parent2)
        child = mutate(child)
        children.append(child)

    # Create new population
    print(children)
    population = np.vstack([elites, children])


1
9
4
0
4
4
6
9
3
6
7
8
1
9
7
3
3
0
5
3
2
9
5
8
1
0
6
3
8
1
2
4
5
3
1
3
[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0]), array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0]), array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1]), array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0]), array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0]), array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0]), array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0]), array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0]), array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0]), array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0]), array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0]), array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0]), array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0])]
5
7
7
7
6
1
6
4
2
8
6
0
1
7
7
0
1
5
6
7
7
7
7
7
1
7
1
7
6
9
2
5
7
7
7
2
[array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1]), array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1]), array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1]), array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1

In [6]:
[0 1 0 1 0 0 1 0 1 1]
[1 1 1 1 1 1 1 1 1 0]
[0 1 1 1 1 1 1 1 1 0]
[1 0 1 1 0 1 0 1 1 0]
[1 0 1 0 0 1 1 0 1 1]